-   repo: local
    hooks:
    - id: golangci-lint
      name: golangci-lint
      description: Fast linters runner for Go.
      entry: golangci-lint run
      types: [go]
      language: golang
      pass_filenames: false
    - id: go-unit-tests
      name: unit testing
      description: "Runs `go test`"
      entry: go test ./...
      types: [go]
      language: golang
      pass_filenames: false
